### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by keyzd** [rrika/cdcEngineDXHR#1]
Hi!

I'm trying to build on Linux, but there's an error:

> [ 38%] Building CXX object CMakeFiles/dxhr.dir/game/ui/FakeScaleform/fakescaleform.cpp.o
> /home/keyzd/cdcEngineDXHR/spinnycube.cpp:406:4: error: use of undeclared identifier 'ImGui_ImplSDL2_ProcessEvent'
>                         ImGui_ImplSDL2_ProcessEvent(&event);
>                         ^
> 1 error generated.
> make[2]: *** [CMakeFiles/dxhr.dir/build.make:76: CMakeFiles/dxhr.dir/spinnycube.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:438: CMakeFiles/dxhr.dir/all] Error 2
> make: *** [Makefile:91: all] Error 2

OS: Arch Linux
CMake version: 3.24.2

**Comment by rrika** [comment]
Hi! I hope this fixes your issue: https://github.com/rrika/cdcEngineDXHR/commit/837d673af7ab67c5543d6f4a626a7fb0209fea85
The "Windows 32-bit binary on Linux" build is generally better tested.

**Comment by keyzd** [comment]
It works, thanks!
