### ISSUE TITLE
crashes on loading certain units

### ISSUE THREAD

**Issue by zemmyang** [rrika/cdcEngineDXHR#3]
I tried opening `det_adam_apt_a`, `pan_hangar`, and `det_sarif_industries` (no units loaded before i open these)

I'd send a log if you can point me to where they're stored

**Comment by rrika** [comment]
You're right. It crashes for me too, so I think I can take it from here.

**Comment by zemmyang** [comment]
just a hunch, but maybe it has something to do with which bigfile is opened? i tried changing the BIGFILE from 000 to 001 and there wasnt any change when i ran the binary again

i noticed in the DRM list that not all the files that should be in the game are present, all i see are pc-w/shaderlibs. comparing it with output from older dxhr unpackers, there should be way more than that.

**Comment by rrika** [comment]
The .000 is truncated from the path, and the individual file open requests are routed to whichever of the bigfiles has the relevant data. (see: https://github.com/rrika/cdcEngineDXHR/blob/main/filesystem/ArchiveFileSystem.cpp#L111) The DRM list only has the files currently loaded.

**Comment by rrika** [comment]
does this resolve the issue? https://github.com/rrika/cdcEngineDXHR/commit/23d7f17907228c264d8c3ae207f00f11e7b84b90

**Comment by zemmyang** [comment]
det_adam_apt_a - loads fine now
det_sarif_industries - still crashes

**Comment by rrika** [comment]
does this resolve the issue? https://github.com/rrika/cdcEngineDXHR/commit/646b9b84e217c05bff93fccc152a016d25cb94fb
(btw, I recommend moving the second IMF slider in the "Loaded units" window upwards while looking at the scene)

**Comment by zemmyang** [comment]
yup, it does. thanks!
