### ISSUE TITLE
output is flipped

### ISSUE THREAD

**Issue by zemmyang** [rrika/cdcEngineDXHR#4]
some shots:

![image](https://user-images.githubusercontent.com/1752285/198831328-16f507a9-5f03-4be4-b148-d9fc29c6160c.png)
![image](https://user-images.githubusercontent.com/1752285/198831444-d727aa7c-22ea-4122-af39-626e45a50d8c.png)

**Comment by rrika** [comment]
this should fix it: https://github.com/rrika/cdcEngineDXHR/commit/afb378aaae85a91349b5de2c16c6da639fefae65

**Comment by zemmyang** [comment]
yup, it's fixed. thanks
